version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1

jobs:
  build:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Install dependencies
          command: npm install && npm audit fix && npm cache clean --force
      - run:
          name: build
          command: yarn build
      - run:
          name: build docker image
          command: docker:build:distroless

workflows:
  version: 2.1
  build:
    jobs:
      - build