version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install && npm audit fix && npm cache clean --force
      - run:
          name: build
          command: yarn build
      - run:
          name: start
          command: yarn start

workflows:
  version: 2.1
  build:
    jobs:
      - build